version: '2'
services:
  web:
    image: 'nginx:alpine'
    container_name: vk-ads-web
    depends_on:
      - php-fpm
    volumes:
      - './nginx/:/etc/nginx/conf.d'
      - '../:/var/www'
    ports:
      - '80:80'
  db:
    container_name: vk-ads-db
    image: mysql:latest
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: vk_ads
    ports:
      - '3306'
  php-fpm:
    build: ./php-fpm
    container_name: vk-ads-fpm
    depends_on:
      - db
    volumes:
      - '../:/var/www:cached'
  scheduler:
    build: ./php-lite
    container_name: vk-ads-scheduler
    entrypoint:
      - bash
      - /usr/app/scheduler.sh
    volumes:
      - '../vk-ads-manager:/var/www'
  queue:
    build: ./php-lite
    container_name: vk-ads-queue
    entrypoint:
      - bash
      - /usr/app/queue.sh
    volumes:
      - '../:/var/www'
volumes:
  db:
    driver: local
